"""Write-once storage for organization backup archives.

An archive is written by whichever process ran the backup job (the API under
local coordination, a worker under Redis) and is later listed, downloaded and
deleted by any API replica, so every process of a deployment must open the
same store: a directory on a volume they all mount, or an S3 prefix
(:mod:`sibyl_core.backends.s3_archive_store`).

Both stores publish an archive once and atomically. A name that already holds
the same bytes reports "already there"; a name that holds different bytes is
an :class:`ArchiveConflict`, never an overwrite. A partly written archive is
never visible under its name: the directory store stages it in a hidden file
and publishes it with a hard link, and S3 shows nothing until PutObject or
CompleteMultipartUpload succeeds.

Archives carry secret material (content recovery keys among it), so names,
sizes and locations may be logged but archive bytes never are.
"""

from __future__ import annotations

import errno
import hashlib
import os
import re
import shutil
import tempfile
from collections.abc import Iterator
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import BinaryIO, Protocol

# Backup ids are generated by the API (backup_<org>_<time>_<nonce>); older
# ids and fixtures use other safe spellings, never path separators.
_BACKUP_ID = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]{0,127}")
_ARCHIVE_NAME = re.compile(r"sibyl_[A-Za-z0-9][A-Za-z0-9_-]{0,127}\.tar\.gz")
# Retention only ever considers archives the backup job names this way.
_RETAINED_NAME = re.compile(r"sibyl_backup_[A-Za-z0-9_-]{1,120}\.tar\.gz")
CHUNK_SIZE = 1024 * 1024


class ArchiveStoreUnavailable(OSError):
    """The archive store failed or refused a request."""


class ArchiveConflict(Exception):
    """The archive name already holds different bytes; nothing was replaced."""


def archive_name(backup_id: str) -> str:
    """The stored name of a backup's archive, refusing anything path-like."""
    if not _BACKUP_ID.fullmatch(backup_id):
        raise ValueError("Backup id is not a valid archive name")
    return f"sibyl_{backup_id}.tar.gz"


def backup_id_of(name: str) -> str:
    check_name(name)
    return name.removeprefix("sibyl_").removesuffix(".tar.gz")


def check_name(name: str) -> str:
    if not _ARCHIVE_NAME.fullmatch(name):
        raise ValueError("Not a backup archive name")
    return name


def retained_name(name: str) -> bool:
    """Whether retention may consider this stored name."""
    return bool(_RETAINED_NAME.fullmatch(name))


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(CHUNK_SIZE), b""):
            digest.update(chunk)
    return digest.hexdigest()


@dataclass(frozen=True)
class ArchiveObject:
    """One published archive as a listing reports it."""

    name: str
    size: int
    modified: datetime


class ArchiveReader(Protocol):
    """An open archive streamed in chunks; close it when done."""

    size: int

    def chunks(self) -> Iterator[bytes]: ...

    def close(self) -> None: ...


class ArchiveStore(Protocol):
    def ready(self) -> None:
        """Fail now, before a backup does its work, if archives cannot be published."""

    def staging_dir(self) -> Path | None:
        """Where a backup should assemble its archive; None means the system temp dir."""

    def location(self, name: str) -> str:
        """Where an archive lives, for records and logs (never a credential)."""

    def put_new(self, name: str, source: Path, *, sha256: str) -> bool:
        """Publish ``source`` under ``name`` once.

        Returns True when created and False when ``name`` already holds the
        same bytes (a retried write that landed). Raises ArchiveConflict when
        it holds different bytes.
        """

    def open(self, name: str) -> ArchiveReader | None:
        """Stream a published archive, or None when there is none."""

    def archives(self) -> list[ArchiveObject]:
        """Every published backup archive, in no particular order."""

    def delete(self, name: str) -> None:
        """Remove an archive; a missing one is already gone."""


def _fsync(path: Path) -> None:
    """Flush a file's data, or a directory's entries, to stable storage."""
    descriptor = os.open(path, os.O_RDONLY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


class _FileReader:
    def __init__(self, handle: BinaryIO) -> None:
        self._handle = handle
        self.size = os.fstat(handle.fileno()).st_size

    def chunks(self) -> Iterator[bytes]:
        try:
            while chunk := self._handle.read(CHUNK_SIZE):
                yield chunk
        finally:
            self.close()

    def close(self) -> None:
        self._handle.close()


class DirectoryArchiveStore:
    """Archives as private files in one directory, published by hard link.

    Every process that writes or serves archives must mount the same
    directory; on Kubernetes that means one claim shared by API and worker,
    ReadWriteMany when replicas run on different nodes.
    """

    def __init__(self, root: Path | str) -> None:
        self._root = Path(root).expanduser()

    def _directory(self) -> Path:
        path = self._root.absolute()
        # Archives hold secrets: a new directory is private. An existing one
        # keeps its mode, so upgrading never breaks a working deployment.
        path.mkdir(mode=0o700, parents=True, exist_ok=True)
        return path

    def _path(self, name: str) -> Path:
        return self._directory() / check_name(name)

    def ready(self) -> None:
        directory = self._directory()
        descriptor, probe = tempfile.mkstemp(prefix=".probe-", dir=directory)
        os.close(descriptor)
        Path(probe).unlink()

    def staging_dir(self) -> Path:
        return self._directory()

    def location(self, name: str) -> str:
        return str(self._directory() / check_name(name))

    def _stage_copy(self, source: Path, directory: Path) -> Path:
        descriptor, staged = tempfile.mkstemp(prefix=".partial-", dir=directory)
        try:
            with os.fdopen(descriptor, "wb") as output, source.open("rb") as handle:
                shutil.copyfileobj(handle, output, CHUNK_SIZE)
        except BaseException:
            Path(staged).unlink(missing_ok=True)
            raise
        return Path(staged)

    def put_new(self, name: str, source: Path, *, sha256: str) -> bool:
        target = self._path(name)
        staged: Path | None = None
        source.chmod(0o600)
        _fsync(source)
        try:
            try:
                os.link(source, target)
            except OSError as error:
                if error.errno != errno.EXDEV:
                    raise
                # Assembled on another filesystem: copy beside the target
                # under a hidden name, then publish that copy by link.
                staged = self._stage_copy(source, target.parent)
                _fsync(staged)
                os.link(staged, target)
        except FileExistsError:
            if sha256_file(target) != sha256:
                raise ArchiveConflict(f"{name} already holds a different archive") from None
            return False
        finally:
            if staged is not None:
                staged.unlink(missing_ok=True)
        _fsync(target.parent)
        return True

    def open(self, name: str) -> ArchiveReader | None:
        path = self._path(name)
        try:
            descriptor = os.open(path, os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0))
        except FileNotFoundError:
            return None
        return _FileReader(os.fdopen(descriptor, "rb"))

    def archives(self) -> list[ArchiveObject]:
        directory = self._directory()
        found: list[ArchiveObject] = []
        with os.scandir(directory) as entries:
            for entry in entries:
                if not retained_name(entry.name) or not entry.is_file(follow_symlinks=False):
                    continue
                try:
                    stat = entry.stat(follow_symlinks=False)
                except FileNotFoundError:
                    continue
                found.append(
                    ArchiveObject(
                        name=entry.name,
                        size=stat.st_size,
                        modified=datetime.fromtimestamp(stat.st_mtime, tz=UTC),
                    )
                )
        return found

    def delete(self, name: str) -> None:
        path = self._path(name)
        path.unlink(missing_ok=True)
        _fsync(path.parent)


__all__ = [
    "ArchiveConflict",
    "ArchiveObject",
    "ArchiveReader",
    "ArchiveStore",
    "ArchiveStoreUnavailable",
    "DirectoryArchiveStore",
    "archive_name",
    "backup_id_of",
    "check_name",
    "retained_name",
    "sha256_file",
]
