# Kong Gateway instance for Sibyl
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: sibyl-gateway
  namespace: sibyl
spec:
  gatewayClassName: kong
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
