"""Public content service contract composed from canonical domain modules."""

from __future__ import annotations

from sibyl_core.models.memory_scope import MemoryScope
from sibyl_core.services.content_client import (
    build_surreal_content_client,
    close_shared_surreal_content_client,
    get_shared_surreal_content_client,
    surreal_content_client,
)
from sibyl_core.services.content_documents import (
    ContentSearchRow,
    get_or_create_source,
    lexical_score,
    lexical_score_from_tokens,
    list_source_ids_for_org,
    list_unlinked_document_chunks,
    load_search_scope,
    search_document_chunks,
    set_source_job_state,
    source_exists,
    tokenize,
    tokenize_fields,
)
from sibyl_core.services.content_lineage import (
    backfill_content_lineage,
    get_raw_memory_lineage,
    materialize_content_lineage,
)
from sibyl_core.services.content_models import (
    AGENT_DIARY_CAPTURE_SURFACE,
    ContentChunk,
    ContentDocument,
    ContentLineageBackfillResult,
    ContentSource,
    RawMemory,
    RawMemoryRecallResult,
    RawMemoryWrite,
    raw_memory_currently_recallable,
    raw_memory_embedding_text,
    raw_memory_recallable,
    reset_raw_memory_embedding_provider_cache,
)
from sibyl_core.services.content_raw_persistence import (
    get_raw_memory,
    get_raw_memory_by_dedupe_key,
    get_raw_memory_by_source_id,
    list_raw_memories_by_source_id,
    list_raw_memories_for_promotion,
    remember_raw_memories,
    remember_raw_memory,
    remember_reflection_candidate_review,
    resolve_raw_memory_prefix,
    save_raw_memory,
)
from sibyl_core.services.content_raw_recall import (
    list_raw_memories_for_scope,
    list_reflection_candidate_reviews,
    list_reflection_dream_source_memories,
    recall_raw_memory,
    recall_raw_memory_with_sources,
)

__all__ = [
    "AGENT_DIARY_CAPTURE_SURFACE",
    "ContentChunk",
    "ContentDocument",
    "ContentLineageBackfillResult",
    "ContentSearchRow",
    "ContentSource",
    "MemoryScope",
    "RawMemory",
    "RawMemoryRecallResult",
    "RawMemoryWrite",
    "backfill_content_lineage",
    "build_surreal_content_client",
    "close_shared_surreal_content_client",
    "get_or_create_source",
    "get_raw_memory",
    "get_raw_memory_by_dedupe_key",
    "get_raw_memory_by_source_id",
    "get_raw_memory_lineage",
    "get_shared_surreal_content_client",
    "lexical_score",
    "lexical_score_from_tokens",
    "list_raw_memories_by_source_id",
    "list_raw_memories_for_promotion",
    "list_raw_memories_for_scope",
    "list_reflection_candidate_reviews",
    "list_reflection_dream_source_memories",
    "list_source_ids_for_org",
    "list_unlinked_document_chunks",
    "load_search_scope",
    "materialize_content_lineage",
    "raw_memory_currently_recallable",
    "raw_memory_embedding_text",
    "raw_memory_recallable",
    "recall_raw_memory",
    "recall_raw_memory_with_sources",
    "remember_raw_memories",
    "remember_raw_memory",
    "remember_reflection_candidate_review",
    "reset_raw_memory_embedding_provider_cache",
    "resolve_raw_memory_prefix",
    "save_raw_memory",
    "search_document_chunks",
    "set_source_job_state",
    "source_exists",
    "surreal_content_client",
    "tokenize",
    "tokenize_fields",
]
