$schema: https://moonrepo.dev/schemas/project.json
language: other
toolchains:
  default: system
tasks:
  lint:
    script: git ls-files -z '*.md' '*.yaml' '*.yml' | xargs -0 npx prettier --check
    inputs:
      - "@group(sources)"
  fix:
    script: git ls-files -z '*.md' '*.yaml' '*.yml' | xargs -0 npx prettier --write
    inputs:
      - "@group(sources)"
    preset: server
  format:
    script: git ls-files -z '*.md' '*.yaml' '*.yml' | xargs -0 npx prettier --write
    inputs:
      - "@group(sources)"
    preset: server
fileGroups:
  sources:
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.md"
layer: configuration
