# CloudNativePG Cluster for Sibyl
# Deploys a single-node PostgreSQL with pgvector extension
# CNPG auto-generates credentials in secret: sibyl-postgres-app
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sibyl-postgres
  namespace: sibyl
spec:
  instances: 1

  # PostgreSQL version with pgvector support
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  # Bootstrap from scratch (CNPG auto-generates password)
  bootstrap:
    initdb:
      database: sibyl
      owner: sibyl
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vector

  # Storage configuration
  storage:
    size: 5Gi
    storageClass: standard # minikube default

  # Resource limits for local dev
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  # Monitoring (disabled for local)
  monitoring:
    enablePodMonitor: false

  # Backup (disabled for local)
  backup:
    barmanObjectStore: null
