"""change_avatar_url_to_text

Revision ID: 442de3d5fb43
Revises: 82eb1c16ee12
Create Date: 2025-12-24 15:29:00.511698

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "442de3d5fb43"
down_revision: str | Sequence[str] | None = "82eb1c16ee12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "avatar_url",
        existing_type=sa.VARCHAR(length=2048),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "avatar_url",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=2048),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
