"""Sync models with database

Revision ID: b0614e6f7ae3
Revises: 706dd0b41342
Create Date: 2025-12-22 21:11:43.182916

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b0614e6f7ae3"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:  # noqa: PLR0915
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_logs",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        "crawl_sources",
        "include_patterns",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "crawl_sources",
        "exclude_patterns",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "crawled_documents",
        "section_path",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "crawled_documents",
        "headings",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "crawled_documents",
        "links",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "crawled_documents",
        "code_languages",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "device_authorization_requests",
        "scope",
        existing_type=sa.VARCHAR(length=255),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "device_authorization_requests",
        "status",
        existing_type=sa.VARCHAR(length=16),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "device_authorization_requests",
        "poll_interval_seconds",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("device_authorization_requests_device_code_hash_key"),
        "device_authorization_requests",
        type_="unique",
    )
    op.drop_constraint(
        op.f("device_authorization_requests_user_code_key"),
        "device_authorization_requests",
        type_="unique",
    )
    op.drop_index(
        op.f("ix_device_authorization_requests_expires_at"),
        table_name="device_authorization_requests",
    )
    op.drop_index(
        op.f("ix_device_authorization_requests_device_code_hash"),
        table_name="device_authorization_requests",
    )
    op.create_index(
        op.f("ix_device_authorization_requests_device_code_hash"),
        "device_authorization_requests",
        ["device_code_hash"],
        unique=True,
    )
    op.drop_index(
        op.f("ix_device_authorization_requests_user_code"),
        table_name="device_authorization_requests",
    )
    op.create_index(
        op.f("ix_device_authorization_requests_user_code"),
        "device_authorization_requests",
        ["user_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_device_authorization_requests_organization_id"),
        "device_authorization_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_authorization_requests_user_id"),
        "device_authorization_requests",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "document_chunks",
        "heading_path",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "document_chunks",
        "entity_ids",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "oauth_connections",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "oauth_connections",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "oauth_connections", "scopes", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=False
    )
    op.alter_column(
        "oauth_connections",
        "connected_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("organization_invitations_token_key"), "organization_invitations", type_="unique"
    )
    op.drop_index(op.f("ix_organization_invitations_token"), table_name="organization_invitations")
    op.create_index(
        op.f("ix_organization_invitations_token"),
        "organization_invitations",
        ["token"],
        unique=True,
    )
    op.drop_constraint(op.f("organizations_slug_key"), "organizations", type_="unique")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.drop_constraint(
        op.f("password_reset_tokens_token_hash_key"), "password_reset_tokens", type_="unique"
    )
    op.drop_index(op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens")
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=True,
    )
    op.alter_column(
        "team_members",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "team_members",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "team_members",
        "joined_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(op.f("team_members_team_id_fkey"), "team_members", type_="foreignkey")
    op.create_foreign_key(None, "team_members", "teams", ["team_id"], ["id"])
    op.alter_column(
        "teams",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "teams",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "teams",
        "is_default",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user_sessions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "user_sessions",
        "token_hash",
        existing_type=sa.VARCHAR(length=64),
        type_=sqlmodel.sql.sqltypes.AutoString(length=128),
        existing_nullable=False,
    )
    op.alter_column(
        "user_sessions",
        "device_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=64),
        existing_nullable=True,
    )
    op.alter_column(
        "user_sessions",
        "browser",
        existing_type=sa.VARCHAR(length=100),
        type_=sqlmodel.sql.sqltypes.AutoString(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "user_sessions",
        "os",
        existing_type=sa.VARCHAR(length=100),
        type_=sqlmodel.sql.sqltypes.AutoString(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "user_sessions",
        "is_current",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_user_sessions_expires_at"), table_name="user_sessions")
    op.drop_constraint(op.f("user_sessions_token_hash_key"), "user_sessions", type_="unique")
    op.create_index(
        op.f("ix_user_sessions_organization_id"), "user_sessions", ["organization_id"], unique=False
    )
    op.alter_column(
        "users",
        "bio",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "timezone",
        existing_type=sa.VARCHAR(length=64),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_github_id_key"), "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:  # noqa: PLR0915
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=False)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(
        op.f("users_github_id_key"), "users", ["github_id"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "users",
        "timezone",
        existing_type=sa.VARCHAR(length=64),
        server_default=sa.text("'UTC'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "bio",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_user_sessions_organization_id"), table_name="user_sessions")
    op.create_unique_constraint(
        op.f("user_sessions_token_hash_key"),
        "user_sessions",
        ["token_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_user_sessions_expires_at"), "user_sessions", ["expires_at"], unique=False
    )
    op.alter_column(
        "user_sessions",
        "is_current",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_sessions",
        "os",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "user_sessions",
        "browser",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "user_sessions",
        "device_type",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "user_sessions",
        "token_hash",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "user_sessions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "teams",
        "is_default",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "teams",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "teams",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "team_members", type_="foreignkey")
    op.create_foreign_key(
        op.f("team_members_team_id_fkey"),
        "team_members",
        "teams",
        ["team_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "team_members",
        "joined_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "team_members",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "team_members",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens")
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("password_reset_tokens_token_hash_key"),
        "password_reset_tokens",
        ["token_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=False)
    op.create_unique_constraint(
        op.f("organizations_slug_key"),
        "organizations",
        ["slug"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_organization_invitations_token"), table_name="organization_invitations")
    op.create_index(
        op.f("ix_organization_invitations_token"),
        "organization_invitations",
        ["token"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("organization_invitations_token_key"),
        "organization_invitations",
        ["token"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "oauth_connections",
        "connected_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "oauth_connections", "scopes", existing_type=postgresql.ARRAY(sa.VARCHAR()), nullable=True
    )
    op.alter_column(
        "oauth_connections",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "oauth_connections",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "document_chunks",
        "entity_ids",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False,
    )
    op.alter_column(
        "document_chunks",
        "heading_path",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_device_authorization_requests_user_id"), table_name="device_authorization_requests"
    )
    op.drop_index(
        op.f("ix_device_authorization_requests_organization_id"),
        table_name="device_authorization_requests",
    )
    op.drop_index(
        op.f("ix_device_authorization_requests_user_code"),
        table_name="device_authorization_requests",
    )
    op.create_index(
        op.f("ix_device_authorization_requests_user_code"),
        "device_authorization_requests",
        ["user_code"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_device_authorization_requests_device_code_hash"),
        table_name="device_authorization_requests",
    )
    op.create_index(
        op.f("ix_device_authorization_requests_device_code_hash"),
        "device_authorization_requests",
        ["device_code_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_authorization_requests_expires_at"),
        "device_authorization_requests",
        ["expires_at"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("device_authorization_requests_user_code_key"),
        "device_authorization_requests",
        ["user_code"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("device_authorization_requests_device_code_hash_key"),
        "device_authorization_requests",
        ["device_code_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "device_authorization_requests",
        "poll_interval_seconds",
        existing_type=sa.INTEGER(),
        server_default=sa.text("5"),
        existing_nullable=False,
    )
    op.alter_column(
        "device_authorization_requests",
        "status",
        existing_type=sa.VARCHAR(length=16),
        server_default=sa.text("'pending'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "device_authorization_requests",
        "scope",
        existing_type=sa.VARCHAR(length=255),
        server_default=sa.text("'mcp'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "crawled_documents",
        "code_languages",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False,
    )
    op.alter_column(
        "crawled_documents",
        "links",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False,
    )
    op.alter_column(
        "crawled_documents",
        "headings",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False,
    )
    op.alter_column(
        "crawled_documents",
        "section_path",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False,
    )
    op.alter_column(
        "crawl_sources",
        "exclude_patterns",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False,
    )
    op.alter_column(
        "crawl_sources",
        "include_patterns",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        server_default=sa.text("'{}'::character varying[]"),
        existing_nullable=False,
    )
    op.alter_column(
        "audit_logs",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        nullable=False,
    )
    # ### end Alembic commands ###
