"""Protected target associations for observations used to derive memory."""

DERIVATION_DEFINITIONS = """
DEFINE TABLE IF NOT EXISTS memory_derivations SCHEMAFULL PERMISSIONS NONE;
DEFINE FIELD IF NOT EXISTS organization_id ON memory_derivations TYPE string;
DEFINE FIELD IF NOT EXISTS target_kind ON memory_derivations TYPE string;
DEFINE FIELD IF NOT EXISTS target_id ON memory_derivations TYPE string;
DEFINE FIELD IF NOT EXISTS body_sha256 ON memory_derivations TYPE string;
DEFINE FIELD IF NOT EXISTS principal_id ON memory_derivations TYPE string;
DEFINE FIELD IF NOT EXISTS authority_ceiling ON memory_derivations TYPE object FLEXIBLE;
DEFINE FIELD IF NOT EXISTS observations ON memory_derivations TYPE array<object> FLEXIBLE;
DEFINE FIELD IF NOT EXISTS active ON memory_derivations TYPE bool;
DEFINE INDEX IF NOT EXISTS memory_derivation_target ON memory_derivations
    FIELDS organization_id, target_kind, target_id UNIQUE;
"""

# Inserted before COMMIT in the existing raw capture transaction. The UUID is
# generated by the capture owner; an association is never accepted from metadata.
STORE_RAW_DERIVATIONS = """
FOR $derivation IN $derivations {
    LET $target = (SELECT * FROM raw_captures WHERE uuid=$derivation.target_id
        AND organization_id=$derivation.organization_id LIMIT 1)[0];
    IF $target = NONE OR crypto::sha256($target.raw_content) != $derivation.body_sha256 {
        THROW 'derivation target changed before association';
    };
    CREATE memory_derivations CONTENT $derivation;
};
"""
