"""Cryptographic utilities for Sibyl.

Provides encryption/decryption for sensitive values stored in the database,
such as API keys in SystemSettings.

Uses Fernet symmetric encryption with a key derived from SIBYL_SETTINGS_KEY
environment variable. If not set, a single process generates and persists a
key on first use. Under Redis coordination several processes (API replicas and
workers) read the same stored settings, so they must share one key: there a
key is never generated, and startup refuses without one.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
import secrets
from functools import lru_cache
from pathlib import Path

import structlog
from cryptography.fernet import Fernet

from sibyl.config import settings

log = structlog.get_logger()

# File to persist auto-generated settings key
_SETTINGS_KEY_FILE = Path.home() / ".sibyl" / "settings.key"


class SettingsKeyError(RuntimeError):
    """No settings key that every process sharing the stored settings agrees on."""


def _shared_key_required() -> SettingsKeyError:
    return SettingsKeyError(
        "SIBYL_SETTINGS_KEY is required when coordination resolves to redis "
        "(SIBYL_COORDINATION_BACKEND=redis, or auto with Redis settings). Every API "
        "replica and worker decrypts the same stored settings, so they must share one "
        "key; a key generated by this process would be its alone, and secrets saved "
        "through any other process would read back as empty here. Generate one with "
        "`openssl rand -hex 32`, set SIBYL_SETTINGS_KEY to that value on every replica "
        f"and worker, and restart. A key file at {_SETTINGS_KEY_FILE} that every process "
        "mounts also works."
    )


def _get_or_create_settings_key() -> bytes:
    """Get encryption key from env var or generate and persist one.

    Priority:
    1. SIBYL_SETTINGS_KEY environment variable
    2. Persisted key in ~/.sibyl/settings.key
    3. Generate new key and persist it (single process only)

    Returns:
        32-byte key suitable for Fernet.

    Raises:
        SettingsKeyError: Under Redis coordination with neither 1 nor 2.
    """
    # 1. Check environment variable
    env_key = os.environ.get("SIBYL_SETTINGS_KEY", "").strip()
    if env_key:
        # Decode from base64 if it looks like base64
        try:
            if len(env_key) == 44 and env_key.endswith("="):
                return base64.urlsafe_b64decode(env_key)
            # Otherwise treat as raw key (32 bytes hex = 64 chars)
            if len(env_key) == 64:
                return bytes.fromhex(env_key)
            # Fall back to using as-is if 32 bytes
            key_bytes = env_key.encode()
            if len(key_bytes) == 32:
                return key_bytes
            # Hash it if wrong length
            return hashlib.sha256(key_bytes).digest()
        except Exception:
            # If decoding fails, hash it
            return hashlib.sha256(env_key.encode()).digest()

    # 2. Check persisted key file
    if _SETTINGS_KEY_FILE.exists():
        try:
            key_data = _SETTINGS_KEY_FILE.read_text().strip()
            return base64.urlsafe_b64decode(key_data)
        except Exception as e:
            log.warning("Failed to read settings key file", error=str(e))

    # 3. Generate new key and persist, only where one process owns the settings
    if settings.resolved_coordination_backend == "redis":
        raise _shared_key_required()
    log.info("Generating new settings encryption key", path=str(_SETTINGS_KEY_FILE))
    key = secrets.token_bytes(32)

    try:
        _SETTINGS_KEY_FILE.parent.mkdir(parents=True, exist_ok=True)
        _SETTINGS_KEY_FILE.write_text(base64.urlsafe_b64encode(key).decode())
        _SETTINGS_KEY_FILE.chmod(0o600)  # Owner read/write only
    except Exception as e:
        log.warning("Failed to persist settings key", error=str(e))

    return key


def require_shared_settings_key() -> None:
    """Refuse to start a multi-process deployment without a shared settings key.

    Decryption failures are logged and read back as empty values, so a
    missing key would otherwise surface as API keys that vanish on some
    replicas. Resolving the key at startup turns it into a refusal instead.
    A single process keeps resolving (and if need be generating) it lazily.
    """
    if settings.resolved_coordination_backend != "redis":
        return
    _get_fernet()


# The message the fingerprint authenticates. Changing it changes every
# fingerprint, so it carries a version.
_FINGERPRINT_MESSAGE = b"sibyl settings key fingerprint v1"


def settings_key_fingerprint() -> str:
    """An HMAC-SHA256 of a fixed message under the settings key.

    Two processes holding the same key produce the same fingerprint and
    different keys produce different ones, while the fingerprint reveals
    nothing that would help recover the key.
    """
    return hmac.new(_settings_key(), _FINGERPRINT_MESSAGE, hashlib.sha256).hexdigest()


@lru_cache(maxsize=1)
def _settings_key() -> bytes:
    return _get_or_create_settings_key()


@lru_cache(maxsize=1)
def _get_fernet() -> Fernet:
    """Get cached Fernet instance for encryption/decryption."""
    # Fernet requires base64-encoded 32-byte key
    return Fernet(base64.urlsafe_b64encode(_settings_key()))


def clear_settings_key_cache() -> None:
    """Forget the resolved key, so the next use resolves it again."""
    _settings_key.cache_clear()
    _get_fernet.cache_clear()


def encrypt_value(plaintext: str) -> str:
    """Encrypt a plaintext string value.

    Args:
        plaintext: The value to encrypt.

    Returns:
        Base64-encoded encrypted ciphertext.
    """
    fernet = _get_fernet()
    ciphertext = fernet.encrypt(plaintext.encode("utf-8"))
    return ciphertext.decode("ascii")


def decrypt_value(ciphertext: str) -> str:
    """Decrypt an encrypted value.

    Args:
        ciphertext: Base64-encoded encrypted value.

    Returns:
        Decrypted plaintext string.

    Raises:
        InvalidToken: If decryption fails (wrong key or corrupted data).
    """
    fernet = _get_fernet()
    plaintext = fernet.decrypt(ciphertext.encode("ascii"))
    return plaintext.decode("utf-8")


def mask_secret(value: str, visible_chars: int = 4) -> str:
    """Mask a secret value for display, showing only last few characters.

    Args:
        value: The secret value to mask.
        visible_chars: Number of characters to show at the end.

    Returns:
        Masked string like "sk-...abc1".
    """
    if not value:
        return ""
    if len(value) <= visible_chars:
        return "*" * len(value)

    # Show prefix if it looks like an API key
    prefix = ""
    if value.startswith("sk-"):
        prefix = "sk-"
        value = value[3:]
    elif value.startswith("sk-ant-"):
        prefix = "sk-ant-"
        value = value[7:]

    visible = value[-visible_chars:]
    return f"{prefix}...{visible}"
