"""Compatibility shim for the legacy startup module path."""

from sibyl import relational_sidecar_startup as _runtime

bootstrap_relational_sidecar_support = _runtime.bootstrap_relational_sidecar_support
bootstrap_legacy_postgres_support = _runtime.bootstrap_legacy_postgres_support
check_relational_sidecar_connection = _runtime.check_relational_sidecar_connection
check_legacy_postgres_connection = _runtime.check_legacy_postgres_connection
run_relational_sidecar_migrations = _runtime.run_relational_sidecar_migrations
run_legacy_postgres_migrations = _runtime.run_legacy_postgres_migrations
recover_relational_sidecar_sources = _runtime.recover_relational_sidecar_sources
recover_legacy_postgres_sources = _runtime.recover_legacy_postgres_sources
load_relational_sidecar_api_keys = _runtime.load_relational_sidecar_api_keys
load_legacy_postgres_api_keys = _runtime.load_legacy_postgres_api_keys

__all__ = [
    "bootstrap_relational_sidecar_support",
    "bootstrap_legacy_postgres_support",
]
