"""Pydantic models for Sibyl knowledge graph operations."""

from sibyl_core.models.entities import (
    ConfigFile,
    Entity,
    EntityType,
    Episode,
    KnowledgeSource,
    Language,
    Pattern,
    Relationship,
    RelationshipType,
    Rule,
    SlashCommand,
    Template,
    Tool,
    Topic,
)
from sibyl_core.models.responses import (
    EntityResponse,
    GraphStatsResponse,
    ListResponse,
    MutationResponse,
    SearchResult,
    SearchResultItem,
)
from sibyl_core.models.sources import (
    Community,
    CrawlStatus,
    Document,
    Source,
    SourceType,
)
from sibyl_core.models.tasks import (
    Epic,
    EpicStatus,
    ErrorPattern,
    Milestone,
    Project,
    ProjectStatus,
    Task,
    TaskComplexity,
    TaskEstimate,
    TaskKnowledgeSuggestion,
    TaskPriority,
    TaskStatus,
    Team,
    TimeEntry,
)
from sibyl_core.models.tools import (
    AddLearningInput,
    GetLanguageGuideInput,
    GetRelatedInput,
    GetTemplateInput,
    ListEntitiesInput,
    RecordDebuggingInput,
    SearchInput,
)

__all__ = [
    # Tool inputs
    "AddLearningInput",
    "GetLanguageGuideInput",
    "GetRelatedInput",
    "GetTemplateInput",
    "ListEntitiesInput",
    "RecordDebuggingInput",
    "SearchInput",
    # Responses
    "EntityResponse",
    "GraphStatsResponse",
    "ListResponse",
    "MutationResponse",
    "SearchResult",
    "SearchResultItem",
    # Base entities
    "ConfigFile",
    "Entity",
    "EntityType",
    "Episode",
    "KnowledgeSource",
    "Language",
    "Pattern",
    "Relationship",
    "RelationshipType",
    "Rule",
    "SlashCommand",
    "Template",
    "Tool",
    "Topic",
    # Task management
    "Epic",
    "EpicStatus",
    "ErrorPattern",
    "Milestone",
    "Project",
    "ProjectStatus",
    "Task",
    "TaskComplexity",
    "TaskEstimate",
    "TaskKnowledgeSuggestion",
    "TaskPriority",
    "TaskStatus",
    "Team",
    "TimeEntry",
    # Documentation crawling
    "Community",
    "CrawlStatus",
    "Document",
    "Source",
    "SourceType",
]
