"""The predicate vocabulary a writing agent may declare, and how to parse it.

Retrieval's graph expansion lane scores every hop by the edge's predicate.
This module owns both that score and hybrid traversal's multiplier so the
write vocabulary and both readers share one meaning for every predicate.

Direction convention
--------------------
Every declared edge runs FROM the memory being written TO the declared target,
because that is the direction the expansion walk follows. `_relation_target_hops`
selects `WHERE source_id IN $source_uuids` and returns `target_id`, so a seed
entity reaches the things it points at, and incoming edges are off by default.
The memory being written is therefore always the grammatical subject:

    remember("Postgres pooling, 2026 rewrite", ..., related_to=["supersedes:ep_0a1b"])

reads "this new memory supersedes ep_0a1b", and mints `new -SUPERSEDES-> ep_0a1b`.
The same convention already governs the one typed edge the system minted before
this module existed: reflection promotion writes
`_relationship(entity_id, superseded_id, RelationshipType.SUPERSEDES)`
(`sibyl_core/services/memory.py`), new row as source, replaced row as target.

The vocabulary
--------------
Closed, and deliberately small. Each entry names a `RelationshipType` that
already exists in the enum, so nothing here widens the schema; `relates_to.name`
is a plain string column and takes these without migration.

===============  ==================  ===================================================
Declaration      RelationshipType    Reads as (subject is the memory being written)
===============  ==================  ===================================================
supersedes       SUPERSEDES          replaces the target; the target is now stale
contradicts      CONTRADICTS         asserts the opposite of the target
requires         REQUIRES            depends on the target being true or done first
supports         SUPPORTS            is evidence for the target's claim or decision
decides          DECIDES             settles the question the target raises
===============  ==================  ===================================================

`caused_by` was considered and left out. No `CAUSED_BY` member exists in
`RelationshipType`, and the expansion weight table would score an invented one
at the 0.64 unknown default, which is exactly what an untyped `RELATED_TO`
already scores. It would cost a schema value and buy no retrieval signal.

`contradicts` is explicit at the fallback scores both readers used before the
canonical policy existed. The predicate keeps both endpoints recallable and
allows either endpoint to reach the other.

Unknown predicates are not an error
-----------------------------------
Anything that is not one of the five above is left alone: the whole string
stays the target id and the edge stays `RELATED_TO`, which is byte-for-byte
what every declaration did before this module existed. Entity ids generated by
`_generate_id` are `<type>_<hex12>` and never contain a colon, so a
colon-bearing string that does not lead with a vocabulary word is far more
likely to be an id shape we do not know about than a typo, and swallowing it
would lose the link entirely.

One ambiguity has no syntactic resolution. `Entity.id` is an unconstrained
string and restore validates whatever a backup carries, so an id spelled
`supersedes:legacy` is representable, and it parses as a declaration naming
`legacy` rather than as itself. Nothing in Sibyl mints an id of that shape, and
telling the two apart needs the store rather than the string, so the parser
takes the declaration reading and this is written down rather than guessed at.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from enum import StrEnum
from types import MappingProxyType

from sibyl_core.models.entities import RelationshipType

__all__ = [
    "DECLARABLE_PREDICATE_HELP",
    "DECLARABLE_RELATIONSHIP_PREDICATES",
    "PREDICATE_EXPANSION_PATH_SCORES",
    "PREDICATE_HYBRID_MULTIPLIERS",
    "PREDICATE_POLICIES",
    "RELATION_DECLARATION_SEPARATOR",
    "SUPPRESSING_RELATIONSHIP_TYPES",
    "PredicateDirection",
    "PredicateLifecycleEffect",
    "PredicatePolicy",
    "RelationDeclaration",
    "declared_relation_targets",
    "parse_relation_declaration",
    "parse_relation_declarations",
    "predicate_direction_allows",
    "predicate_policy",
]

RELATION_DECLARATION_SEPARATOR = ":"

DECLARABLE_RELATIONSHIP_PREDICATES: MappingProxyType[str, RelationshipType] = MappingProxyType(
    {
        "supersedes": RelationshipType.SUPERSEDES,
        "contradicts": RelationshipType.CONTRADICTS,
        "requires": RelationshipType.REQUIRES,
        "supports": RelationshipType.SUPPORTS,
        "decides": RelationshipType.DECIDES,
    }
)


class PredicateDirection(StrEnum):
    """Allowed traversal direction from the reader's current frontier."""

    EXISTING = "existing"
    OUTGOING = "outgoing"
    INCOMING = "incoming"
    BOTH = "both"


class PredicateLifecycleEffect(StrEnum):
    """Lifecycle meaning carried by a predicate declaration."""

    NONE = "none"
    HIDE_TARGET = "hide_target"
    MARK_CONTESTED = "mark_contested"


@dataclass(frozen=True, slots=True)
class PredicatePolicy:
    """One relationship's score, direction, lifecycle, and receipt contract."""

    hybrid_multiplier: float | None
    expansion_path_score: float | None
    direction: PredicateDirection = PredicateDirection.EXISTING
    lifecycle_effect: PredicateLifecycleEffect = PredicateLifecycleEffect.NONE
    receipt_label: str = ""


def _policy(
    name: str,
    *,
    hybrid: float | None = None,
    expansion: float | None = None,
    direction: PredicateDirection = PredicateDirection.EXISTING,
    lifecycle: PredicateLifecycleEffect = PredicateLifecycleEffect.NONE,
) -> PredicatePolicy:
    return PredicatePolicy(
        hybrid_multiplier=hybrid,
        expansion_path_score=expansion,
        direction=direction,
        lifecycle_effect=lifecycle,
        receipt_label=name.lower(),
    )


# The union of every relationship with an engine-specific score. A missing
# score means that engine keeps its existing unknown-predicate default rather
# than borrowing the other engine's numeric unit.
PREDICATE_POLICIES: MappingProxyType[str, PredicatePolicy] = MappingProxyType(
    {
        "ABOUT": _policy("ABOUT", expansion=0.78),
        "APPLIES_TO": _policy("APPLIES_TO", hybrid=1.10),
        "BELONGS_TO": _policy("BELONGS_TO", hybrid=1.20, expansion=0.72),
        "BLOCKS": _policy("BLOCKS", hybrid=1.25, expansion=0.96),
        "BREAKS": _policy("BREAKS", hybrid=1.15),
        "CONFLICTS_WITH": _policy("CONFLICTS_WITH", hybrid=1.10),
        "CONTAINS": _policy("CONTAINS", hybrid=1.10, expansion=0.72),
        "CONTRADICTS": _policy(
            "CONTRADICTS",
            hybrid=1.00,
            expansion=0.64,
            direction=PredicateDirection.BOTH,
            lifecycle=PredicateLifecycleEffect.MARK_CONTESTED,
        ),
        "DECIDES": _policy(
            "DECIDES",
            hybrid=1.00,
            expansion=1.00,
            direction=PredicateDirection.OUTGOING,
        ),
        "DEPENDS_ON": _policy("DEPENDS_ON", hybrid=1.25, expansion=0.98),
        "DERIVED_FROM": _policy("DERIVED_FROM", hybrid=1.05, expansion=0.70),
        "DOCUMENTED_IN": _policy("DOCUMENTED_IN", hybrid=1.00, expansion=0.66),
        "ENABLES": _policy("ENABLES", hybrid=1.15),
        "ENCOUNTERED": _policy("ENCOUNTERED", hybrid=1.10, expansion=0.86),
        "IMPLEMENTED": _policy("IMPLEMENTED", hybrid=1.15, expansion=0.90),
        "MENTIONS": _policy("MENTIONS", hybrid=0.35, expansion=0.58),
        "PRODUCES": _policy("PRODUCES", expansion=0.82),
        "REFERENCES": _policy("REFERENCES", hybrid=1.15, expansion=0.86),
        "RELATED_TO": _policy("RELATED_TO", hybrid=0.85, expansion=0.64),
        "REQUIRES": _policy(
            "REQUIRES",
            hybrid=1.15,
            expansion=0.98,
            direction=PredicateDirection.OUTGOING,
        ),
        "SHARES_COMMUNITY": _policy("SHARES_COMMUNITY", expansion=0.74),
        "SUPERSEDES": _policy(
            "SUPERSEDES",
            hybrid=1.10,
            expansion=0.95,
            direction=PredicateDirection.INCOMING,
            lifecycle=PredicateLifecycleEffect.HIDE_TARGET,
        ),
        "SUPPORTS": _policy(
            "SUPPORTS",
            hybrid=1.00,
            expansion=0.94,
            direction=PredicateDirection.OUTGOING,
        ),
        "TOUCHES": _policy("TOUCHES", expansion=0.82),
        "USES_PROCEDURE": _policy("USES_PROCEDURE", hybrid=1.15, expansion=0.92),
        "VALIDATED_BY": _policy("VALIDATED_BY", hybrid=1.15, expansion=0.94),
    }
)

PREDICATE_HYBRID_MULTIPLIERS: MappingProxyType[str, float] = MappingProxyType(
    {
        name: policy.hybrid_multiplier
        for name, policy in PREDICATE_POLICIES.items()
        if policy.hybrid_multiplier is not None
    }
)
PREDICATE_EXPANSION_PATH_SCORES: MappingProxyType[str, float] = MappingProxyType(
    {
        name: policy.expansion_path_score
        for name, policy in PREDICATE_POLICIES.items()
        if policy.expansion_path_score is not None
    }
)


def predicate_policy(predicate: object) -> PredicatePolicy | None:
    name = str(getattr(predicate, "value", predicate) or "").upper()
    return PREDICATE_POLICIES.get(name)


def predicate_direction_allows(
    predicate: object,
    direction: str,
    *,
    existing_default: bool = True,
) -> bool:
    """Apply declared direction while preserving unspecified engine behavior."""

    policy = predicate_policy(predicate)
    if policy is None or policy.direction is PredicateDirection.EXISTING:
        return existing_default
    normalized = str(direction).lower()
    return policy.direction is PredicateDirection.BOTH or policy.direction.value == normalized


# The two predicates that assert the target is wrong rather than merely
# related. Retrieval demotes or hides what they point at, so declaring one is a
# claim about someone else's memory and the write surface authorizes the target
# before minting it. The other three only raise a traversal weight, which is no
# more consequential than the untyped link an agent could already write.
SUPPRESSING_RELATIONSHIP_TYPES = frozenset(
    {RelationshipType.SUPERSEDES, RelationshipType.CONTRADICTS}
)

# Rendered into tool descriptions and field help so a model reading the schema
# sees the closed set and the direction in one line.
DECLARABLE_PREDICATE_HELP = (
    "Entity IDs to link. A bare ID creates an untyped RELATED_TO edge. "
    "Prefix an ID with a predicate to declare what this memory does to that "
    "one, which is what retrieval weights when it walks the graph: "
    '"supersedes:<id>" (this replaces that), "contradicts:<id>", '
    '"requires:<id>", "supports:<id>" (this is evidence for that), '
    '"decides:<id>" (this settles that). The memory being written is always '
    "the subject. Any other prefix is treated as part of the ID and links "
    "untyped."
)


@dataclass(frozen=True, slots=True)
class RelationDeclaration:
    """One parsed `related_to` entry.

    `target_id` is what the edge points at and what any existence or access
    check must run against; `declared` records whether the predicate came from
    the writer or is the untyped fallback.
    """

    target_id: str
    relationship_type: RelationshipType
    declared: bool

    @property
    def edge_slug(self) -> str:
        """Lowercase predicate for the deterministic relationship id."""
        return self.relationship_type.value.lower()


def _is_plausible_entity_id(value: str) -> bool:
    """Whether a string could be an entity id rather than prose or a fragment.

    Ids are opaque strings, so this cannot be exact. It rejects the shapes that
    are certainly not a single id: empty, internally separated, or carrying
    whitespace, which is what a mistyped declaration or a stray URL looks like.
    """
    if not value or RELATION_DECLARATION_SEPARATOR in value:
        return False
    return not any(character.isspace() for character in value)


def parse_relation_declaration(value: str) -> RelationDeclaration:
    """Split one `related_to` entry into a predicate and a target id.

    The prefix has to match a vocabulary word exactly and the remainder has to
    look like a single id, so `https://x/y` and `requires:a:b` stay whole
    rather than being torn into a predicate and a fragment.
    """
    text = str(value).strip()
    prefix, separator, remainder = text.partition(RELATION_DECLARATION_SEPARATOR)
    if not separator:
        return RelationDeclaration(text, RelationshipType.RELATED_TO, declared=False)

    relationship_type = DECLARABLE_RELATIONSHIP_PREDICATES.get(prefix.strip().lower())
    target_id = remainder.strip()
    if relationship_type is None or not _is_plausible_entity_id(target_id):
        return RelationDeclaration(text, RelationshipType.RELATED_TO, declared=False)
    return RelationDeclaration(target_id, relationship_type, declared=True)


def parse_relation_declarations(values: Iterable[str] | None) -> list[RelationDeclaration]:
    """Parse a whole `related_to` list, dropping blanks."""
    return [parse_relation_declaration(value) for value in values or () if str(value).strip()]


def declared_relation_targets(values: Sequence[str] | None) -> list[str]:
    """The entity ids a `related_to` list actually points at, predicates removed.

    Callers that validate targets or count links want the ids, not the
    declarations that carry them.
    """
    return [declaration.target_id for declaration in parse_relation_declarations(values)]
