/**
 * Public API client contract.
 *
 * Domain implementations live in `./api/*`. Keep this barrel explicit so the
 * compatibility surface remains reviewable and type-only exports stay erased.
 */

export type {
  AdminAuditEvent,
  AdminAuditExportFormat,
  AdminAuditListResponse,
  AdminAuditParams,
  AIModelEntry,
  AIModelKind,
  AIRegistryResponse,
  ApiKeyValidation,
  BackgroundJobListResponse,
  BackgroundJobStatus,
  BackgroundJobSummary,
  BackupData,
  BackupInfo,
  BackupJobStatus,
  BackupListResponse,
  BackupResponse,
  BackupSettingsResponse,
  BackupSettingsUpdate,
  BackupStatus,
  CleanupResponse,
  CreateBackupRequest,
  CreateBackupResponse,
  DeleteSettingResponse,
  HealthResponse,
  IntegrationResponse,
  LLMConfigSource,
  LLMConfigValueField,
  LLMProviderName,
  LLMSecretConfigField,
  LLMSettingsResponse,
  LLMSurface,
  LLMSurfaceSettings,
  LLMTestResult,
  LLMValidationStatus,
  MaintenanceJobResponse,
  McpClientConfig,
  ModelAvailabilityTestResult,
  ProviderKeyTestResult,
  RestoreResponse,
  SettingInfo,
  SettingsResponse,
  SetupStatus,
  StatsResponse,
  TelemetryDurationSummary,
  TelemetryEvent,
  TelemetryMetric,
  TelemetrySummaryResponse,
  TelemetryTrendPoint,
  UpdateLLMSurfaceRequest,
  UpdateLLMSurfaceResponse,
  UpdateSettingsRequest,
  UpdateSettingsResponse,
} from './api/admin';
export { isSetupAlreadyInitializedError } from './api/admin';
export type {
  ApiKey,
  ApiKeyCreateRequest,
  ApiKeyCreateResponse,
  ApiKeysResponse,
  AuthMeResponse,
  AuthProvider,
  AuthProvidersResponse,
  OnboardingChecklist,
  OrgCreateRequest,
  OrgCreateResponse,
  OrgGetResponse,
  OrgInvitation,
  OrgInvitationCreateRequest,
  OrgInvitationCreateResponse,
  OrgInvitationsResponse,
  OrgListResponse,
  OrgMember,
  OrgMembersResponse,
  OrgSummary,
  OrgSwitchResponse,
  OrgUpdateRequest,
  PasswordChangeRequest,
  PasswordResetConfirmRequest,
  PasswordResetRequest,
  PreferencesResponse,
  Session,
  SessionsResponse,
  UserPreferences,
  UserProfile,
} from './api/auth';
export { api } from './api/client';
export type {
  ClusterEdge,
  Entity,
  EntityCreate,
  EntityGetParams,
  EntityListResponse,
  EntityUpdate,
  GraphNodeMetadata,
  GraphResolution,
  HierarchicalCluster,
  HierarchicalEdge,
  HierarchicalGraphResponse,
  HierarchicalNode,
  RelatedEntitySummary,
} from './api/graph';
export type {
  MemoryAuditEvent,
  MemoryAuditListResponse,
  MemoryCorrectionAction,
  MemoryCorrectionRequest,
  MemoryCorrectionResponse,
  MemoryDerivedRecord,
  MemoryScope,
  MemorySourceInspectResponse,
  MemorySpace,
  MemorySpaceListResponse,
  MemorySpaceMember,
  RawCapture,
  RawCaptureListResponse,
  RawCaptureReviewState,
  RawCaptureSummary,
  SessionBundleContext,
  SessionBundleResponse,
  SessionMemorySummary,
  SessionTaskSummary,
  SourceAdapter,
  SourceAdapterListResponse,
  SourceImportProgress,
  SourceImportResumeRequest,
  SourceImportStartRequest,
  SourceImportStatus,
  SourceImportStatusResponse,
  SynthesisArtifact,
  SynthesisArtifactFormat,
  SynthesisDepth,
  SynthesisDraftRequest,
  SynthesisDraftResponse,
  SynthesisGap,
  SynthesisOutline,
  SynthesisOutlineSection,
  SynthesisOutputType,
  SynthesisPlanResponse,
  SynthesisRequest,
  SynthesisRunStatus,
  SynthesisSectionRequest,
  SynthesisSourcePack,
  SynthesisSourceReference,
  SynthesisVerification,
  SynthesisVerificationStatus,
} from './api/memory';
export type { EntityMetadataMap } from './api/metadata';
export type {
  CodeExampleParams,
  CodeExampleResponse,
  CodeExampleResult,
  DocumentRelatedEntitiesResponse,
  DocumentRelatedEntity,
  DocumentUpdateRequest,
  EntitySortField,
  FullPageResponse,
  RAGChunkResult,
  RAGPageResult,
  RAGSearchParams,
  RAGSearchResponse,
  SearchResponse,
  SearchResult,
  SearchResultMetadata,
  SortOrder,
} from './api/search';
export type { BaseMetadata } from './api/shared';
export type {
  CrawlSource,
  CrawlStatus,
  LocalSourceData,
  Source,
  SourceListResponse,
  SourceMetadata,
  SourceSummary,
  SourceType,
} from './api/sources';
export type {
  AssigneeStats,
  AuthorType,
  CreateNoteRequest,
  Epic,
  EpicActionResponse,
  EpicListResponse,
  EpicMetadata,
  EpicProgress,
  EpicStatus,
  EpicSummary,
  Note,
  NotesListResponse,
  OrgMetricsResponse,
  Project,
  ProjectMember,
  ProjectMembersResponse,
  ProjectMetadata,
  ProjectMetrics,
  ProjectMetricsResponse,
  ProjectRole,
  ProjectSummariesResponse,
  ProjectSummary,
  Task,
  TaskActionResponse,
  TaskListResponse,
  TaskMetadata,
  TaskPriority,
  TaskPriorityDistribution,
  TaskStatus,
  TaskStatusDistribution,
  TaskSummary,
  TimeSeriesPoint,
} from './api/work-items';
